export { HomePage } from './HomePage'
export { AboutPage } from './AboutPage'
export { ProjectsPage } from './ProjectsPage'
export { ExperiencePage } from './ExperiencePage'
export { ContactPage } from './ContactPage'
export { NotFoundPage } from './NotFoundPage'
